# Generated by Django 5.0.6 on 2024-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawl_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
